# Generated by Django 6.0.3 on 2026-04-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_employee_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workcode',
            name='requires_job',
            field=models.BooleanField(default=True),
        ),
    ]
