# Generated by Django 6.0.3 on 2026-04-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workcode_is_active_workcode_requires_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_code',
        ),
    ]
