# Generated by Django 6.0.3 on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_employee_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('jobs', 'Jobs'), ('employees', 'Employees'), ('work_codes', 'Work Codes'), ('non_job_codes', 'Non Job Codes')], max_length=32, unique=True)),
                ('last_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_uploaded_filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
