# Generated by Django 6.0.3 on 2026-05-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_referencedataupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
